### ISSUE TITLE
switch to sqlalchemy 1.4

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/timvt#35]
Supporting custom functions (#8 #34) is difficult with `asyncpg` because it doesn't support named parameters, making it hard to forward query parameters to the custom function.  Sqlalchemy 1.4 [supports asyncio](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html) (via asyncpg) but also has a DBAPI integration which allows for named parameters.

**Comment by geospatial-jeff** [comment]
Expanding my thoughts a little.

Custom functions are a really important thing to get right.  pg_tileserv/martin both provide a nice interface where functions accept params of `x` `y` `z`, and `**query_params`.  This provides a lot of flexibility and is trivial to implement with anything that supports [PEP 249](https://legacy.python.org/dev/peps/pep-0249/#paramstyle).  Without a PEP249 implementation (ex. asyncpg) it becomes not so trivial because we need to be concerned with ordering of the query params.

The downside of course is that timvt will be very slightly slower.  But I think as long as we use sqlalchemy core and stick to native SQL the performance loss should be minimal, as we only care to take advantage of the named parameters/tokenization provided by sqlalchemy.

When I think of the tradeoffs between supporting more complex custom functions and performance I lean towards the former.

**Comment by vincentsarago** [comment]
my experience with PG is somehow inexistant so I'll defer to @bitner and maybe @sharkinsspatial ;-)

**Comment by bitner** [comment]
Yeah, named parameters are definitely great. I don't think we want to rely on the ORM functionality of SQLAlchemy since we really want tight control of our SQL here. A lighter weight option that uses asyncpg and provides named parameter support is https://github.com/samuelcolvin/buildpg (build by Samuel Colvin of pydantic fame). I've been using that library quite a bit just for the named parameter support.

**Comment by geospatial-jeff** [comment]
closing in favor of #37
