### ISSUE TITLE
include schema in list of layers on landing page

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/timvt#45]
Currently only the table name is included

**Comment by vincentsarago** [comment]
@geospatial-jeff I'm not sure to understand this 

Note: 
you can use either `schema.table_name` or `table_name` alone as parameter. 

https://github.com/developmentseed/timvt/blob/05e08b1c63414ed2b30f24d3cae3c1f304ee76ed/timvt/dependencies.py#L47-L52

**Comment by geospatial-jeff** [comment]
Oh I just saw that the schema isn't present in the list of layers on the landing page.  Should the schema names be included there too?  

`Demo for {schema}.{table}`

**Comment by vincentsarago** [comment]
yeah, I always felt that it was cleaner to have `{schema}.{table}`, and can't remember why we didn't do it directly cc @bitner

**Comment by bitner** [comment]
@vincentsarago I'm not sure that was ever an intentional decision
