### ISSUE TITLE
specify default min/max zooms

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/timvt#46]
Allow the user to specify default min/max zooms

https://github.com/CrunchyData/pg_tileserv/blob/master/config/pg_tileserv.toml.example#L57-L61

**Comment by vincentsarago** [comment]
@geospatial-jeff bounds depends on the TMS. by default we fallback to the TMS min/max zoom but you can overwrite those using query parameters in the tilejson endpoint 
https://github.com/developmentseed/timvt/blob/05e08b1c63414ed2b30f24d3cae3c1f304ee76ed/timvt/endpoints/factory.py#L146-L147

I think we just need to document this ?

**Comment by geospatial-jeff** [comment]
Overwriting with query parameters is fine, and I agree should be documented.  But having an override is nice too because often times you want to set a sensible min/max zoom based on the scale of your data, rather than falling back to the TMS defaults.  For example. min/max zoom of 0/30 doesn't make sense for a building footprint dataset, and the caller may not be familiar enough with the scale of the dataset to determine appropriate min/max zooms themselves.

pg_tileserv allows this with a config variable that adds a default min/max zoom to all layers, which I think is a nice and simple way of doing this.  Something like `minzoom or (default_minzoom or tms.minzoom)`.
