### ISSUE TITLE
No tile produce when Tile Matrix Set is WorldCRS84Quad

### ISSUE THREAD

**Issue by dayxero** [developmentseed/timvt#65]
To query for tiles when `Tile Matrix Set` is set to `WorldCRS84Quad`, there  is no tile produced. It is cause by the `None` value which is returned from `tms.crs.to_epsg()`.  Actually, the `None` value is produced from package `morecantile`, as we can see using the code below.

```python
tms = morecantile.tms.get("WorldCRS84Quad")
print(tms.crs.to_epsg())
# None
```

To avoid this error, I change the code as following diff result for the file `timvt/layer.py`:

```diff
diff --git a/timvt/layer.py b/timvt/layer.py
index 2ab3460..af51b5e 100644
--- a/timvt/layer.py
+++ b/timvt/layer.py
@@ -150,13 +150,15 @@ class Table(Layer):
                 )
                 SELECT ST_AsMVT(mvtgeom.*) FROM mvtgeom
             """
+            epsg = tms.crs.to_epsg()
+            if epsg is None: epsg = 4326
             return await conn.fetchval_b(
                 sql_query,
                 xmin=bbox.left,
                 ymin=bbox.bottom,
                 xmax=bbox.right,
                 ymax=bbox.top,
-                epsg=tms.crs.to_epsg(),
+                epsg=epsg,
                 seg_size=segSize,
                 tile_resolution=int(resolution),
                 tile_buffer=int(buffer),
```

**Comment by vincentsarago** [comment]
😬 you are right...

I'll look at it today (and add tests 🤦) 🙏

**Comment by dayxero** [comment]
Thanks. I like `TiMVT` support different `Tile Matrix Set`. Keep doing good things :muscle:.

**Comment by vincentsarago** [comment]
@dayxero while I wait for #66 to be merged, I just published a new version of morecantile with `WGS1984Quad` TileMatrixSet (epsg4326) which should then run without issue 

https://github.com/developmentseed/morecantile/blob/master/CHANGES.md#303-2021-12-06
