### ISSUE TITLE
Function Sources ?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/timvt#8]
ref: 
- https://github.com/urbica/martin#function-sources
- https://github.com/CrunchyData/pg_tileserv#function-layers

**Comment by bitner** [comment]
So, I think an interesting approach for this would be to have a .sql file that gets read/scanned using 
https://github.com/nackjicholson/aiosql

Where any query (which could be a select * from function(...)) in that file that has the :x,:y,:z parameters set is made available and exposed using the name attribute from the comment string.

By default, these queries would not allow column filtering unless a DataClass was set.

**Comment by vincentsarago** [comment]
done in #59
