### ISSUE TITLE
tables outside of public schema in postgres

### ISSUE THREAD

**Issue by MiroslavHrcan** [developmentseed/timvt#91]
Hi,

I'm trying to get tables from other schema than public (http://localhost:8081/tables.json), but it keeps ignore them.

I tried even to move postgis to that another schema, https://postgis.net/2017/11/07/tip-move-postgis-schema/, but nothing happened. Also, rights for that schema, table and specific user are granted.

Am I skipping something?

Best regards and thanks for awesome project.

**Comment by geospatial-jeff** [comment]
I believe you can fix this on the database side by including your schema in the search path (https://gis.stackexchange.com/questions/354523/use-postgis-functions-from-an-other-schema-than-public).

Something like this:
```sql
SET search_path TO public, schema1, schema2
```

There may be a solution in timvt itself but not sure.

**Comment by vincentsarago** [comment]
there is a solution directly in `timvt`

in https://github.com/developmentseed/timvt/blob/master/timvt/db.py#L51 you need to pass `schemas=["public", ....]` 
I'll push a changes in couple minutes so this can be set by environment variable

**Comment by MiroslavHrcan** [comment]
@geospatial-jeff  thx for the response, but I have already tried this and it did not work for this problem.

@vincentsarago  I will try after you push this, thank you very much

**Comment by vincentsarago** [comment]
@MiroslavHrcan please install timvt from `master` and set `PG_SCHEMAS='["public", ...]'` in your environment 

```
DB_SCHEMAS='["pgstac","public"]' uvicorn timvt.main:app
```

**Comment by MiroslavHrcan** [comment]
just to confirm that it works, thx
