### ISSUE TITLE
Use OGCAPI-Tiles standard?

### ISSUE THREAD

**Issue by KoalaGeo** [developmentseed/timvt#99]
Would you consider using the [OGCAPI-Tiles](https://ogcapi.ogc.org/tiles/) spec for tile delivery?

The standards an update/refresh on the web map tile service standard, a number of clients are already available including Openlayers - https://github.com/openlayers/openlayers/pull/10963

**Comment by vincentsarago** [comment]
👋 @KoalaGeo , as far I can see the spec is still in `draft` mode but this is something we might decide once we work on #96

**Comment by vincentsarago** [comment]
😅 

> maybe we should wait for https://ogcapi.ogc.org/tiles/

I already wrote☝️ in #96

**Comment by KoalaGeo** [comment]
Nice! 😁

**Comment by vincentsarago** [comment]
maybe in https://github.com/developmentseed/tipg
